version: 2
updates:
  # Enable version updates for yarn
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    groups:
      webpack:
        patterns:
          - "webpack*"
      eslint:
        patterns:
          - "eslint*" # Update all packages together if they start with "eslint"
          - "@types/eslint" # eslint types
          - "@typescript-eslint/*" # eslint typescript
        update-types:
        - "minor"
        - "patch"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"