name: "Build & Deploy"

on:
  push:
    branches: 
      - 'feature/**' # match an pushes on feature/* and feature/<any sub branch>/*
      - main
    paths-ignore: # don't run when changes made to these folders 
      - '.vscode/**'
      - 'GitVersion.yml'
      - '.eslintrc.json'
      - 'test/**'
    
jobs:
  cicd:
    name: CI/CD
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: fetch all history and tags from all branches for gitversion
        run: git fetch --prune --unshallow

      - name: install gitversion tool
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
            versionSpec: '5.x'
      
      - name: execute gitversion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.11.0
        
      - name: print gitversion
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
        
      - name: clean install dependencies
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install
          args: --frozen-lockfile

      - name: update metadata in package.json
        uses: onlyutkarsh/patch-files-action@v1.0.5
        with:
          files: '${{github.workspace}}/package.json'
          patch-syntax: |
            = /version => "${{ steps.gitversion.outputs.majorMinorPatch }}"
            = /displayName => "PowerApps Portal Local Development"
            = /description => "Local source control for Power Apps portals code for web files like images or style sheets, web templates and content snippets."
      
      - name: add version in CHANGELOG.md
        uses: cschleiden/replace-tokens@v1
        with:
          files: '${{github.workspace}}/CHANGELOG.md'
        env:
          VERSION: "${{ steps.gitversion.outputs.majorMinorPatch }}"

      - name: compile and create vsix
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: vsce-package

      - name: print vsix path
        run: |
          echo "VSIX Path: ${{ env.vsix_path }}"

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v4
        with:
          name: t200-logs-${{steps.gitversion.outputs.majorMinorPatch}}.vsix
          path: ${{github.workspace}}/t200-logs-${{steps.gitversion.outputs.majorMinorPatch}}.vsix

      - name: create a release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.gitversion.outputs.majorMinorPatch }}
          release_name: v${{ steps.gitversion.outputs.majorMinorPatch }}